# _config.yml

# Site settings
title: Mig Studio Site
description: A brief description of your site

# Build settings
markdown: kramdown
exclude: ['node_modules', 'vendor', '.sass-cache', '_site', '.git', '.github']
include: ['.s', '_cs','_nw','_ph','_pu','_s1','_sh','_si','_spt','_st']

# Cache control configurations
defaults:
  - scope:
      path: ""
    values:
      cache_control: "max-age=604800"
