[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Encoding = "gzip, deflate, br"
    Content-Length = "totalBytes"
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Encoding = "gzip, deflate, br"
    Content-Length = "totalBytes"
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Encoding = "deflate, br"
    Content-Length = "totalBytes"
[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Encoding = "deflate, br"
    Content-Length = "totalBytes"
[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Encoding = "deflate, br"
    Content-Length = "totalBytes"
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Encoding = "deflate, br"
    Content-Length = "totalBytes"
