[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
      Access-Control-Allow-Methods = "GET, PUT, POST, DELETE"
      Access-Control-Allow-Headers = "Content-Type"
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]                                                                      
  for = "/bundle/bundle.js.gz"                                                             
  [headers.values]
    Content-Encoding = "gzip, deflate, br"
[[headers]]                                                                      
  for = "/bundle/bundle_gzip.js"                                                             
  [headers.values]
    Content-Encoding = "gzip, deflate, br"
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
